# Form implementation generated from reading ui file '.\delete.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Delete(object):
    def setupUi(self, Dialog_Delete):
        Dialog_Delete.setObjectName("Dialog_Delete")
        Dialog_Delete.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog_Delete.resize(530, 190)
        Dialog_Delete.setMinimumSize(QtCore.QSize(530, 190))
        Dialog_Delete.setMaximumSize(QtCore.QSize(530, 190))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/app-icon/dex-icon-512x512.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        Dialog_Delete.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_Delete)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_Delete)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_Column_List_Select = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_Column_List_Select.setObjectName("comboBox_Column_List_Select")
        self.verticalLayout.addWidget(self.comboBox_Column_List_Select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_Apply_Delete_Column = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Apply_Delete_Column.setAutoDefault(False)
        self.pushButton_Apply_Delete_Column.setObjectName("pushButton_Apply_Delete_Column")
        self.verticalLayout.addWidget(self.pushButton_Apply_Delete_Column)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_Delete)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinBox_Row_Number_Select = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBox_Row_Number_Select.setWrapping(True)
        self.spinBox_Row_Number_Select.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_Row_Number_Select.setSuffix("")
        self.spinBox_Row_Number_Select.setMinimum(-1)
        self.spinBox_Row_Number_Select.setProperty("value", -1)
        self.spinBox_Row_Number_Select.setObjectName("spinBox_Row_Number_Select")
        self.verticalLayout_2.addWidget(self.spinBox_Row_Number_Select)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_Apply_Delete_Row = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_Apply_Delete_Row.setAutoDefault(False)
        self.pushButton_Apply_Delete_Row.setObjectName("pushButton_Apply_Delete_Row")
        self.verticalLayout_2.addWidget(self.pushButton_Apply_Delete_Row)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_Info = QtWidgets.QLabel(parent=Dialog_Delete)
        self.label_Info.setText("")
        self.label_Info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Info.setObjectName("label_Info")
        self.verticalLayout_3.addWidget(self.label_Info)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Dialog_Delete)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_Cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_Delete)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Delete)

    def retranslateUi(self, Dialog_Delete):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Delete.setWindowTitle(_translate("Dialog_Delete", "Usuń"))
        self.groupBox.setTitle(_translate("Dialog_Delete", "Kolumny"))
        self.comboBox_Column_List_Select.setPlaceholderText(_translate("Dialog_Delete", "Wybierz kolumnę..."))
        self.pushButton_Apply_Delete_Column.setText(_translate("Dialog_Delete", "Usuń kolumnę"))
        self.groupBox_2.setTitle(_translate("Dialog_Delete", "Wiersze"))
        self.spinBox_Row_Number_Select.setSpecialValueText(
            _translate("Dialog_Delete", "Wybierz numer wiersza od \'0\' do \'0\': "))
        self.spinBox_Row_Number_Select.setPrefix(_translate("Dialog_Delete", "Numer wiersza: "))
        self.pushButton_Apply_Delete_Row.setText(_translate("Dialog_Delete", "Usuń wiersz"))
        self.pushButton_Cancel.setText(_translate("Dialog_Delete", "Anuluj"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog_Delete = QtWidgets.QDialog()
    ui = Ui_Dialog_Delete()
    ui.setupUi(Dialog_Delete)
    Dialog_Delete.show()
    sys.exit(app.exec())
