# Form implementation generated from reading ui file '.\get-dummies.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Get_Dummies(object):
    def setupUi(self, Dialog_Get_Dummies):
        Dialog_Get_Dummies.setObjectName("Dialog_Get_Dummies")
        Dialog_Get_Dummies.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog_Get_Dummies.resize(400, 105)
        Dialog_Get_Dummies.setMinimumSize(QtCore.QSize(400, 105))
        Dialog_Get_Dummies.setMaximumSize(QtCore.QSize(400, 105))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/app-icon/dex-icon-512x512.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        Dialog_Get_Dummies.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Get_Dummies)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_Select_Data = QtWidgets.QComboBox(parent=Dialog_Get_Dummies)
        self.comboBox_Select_Data.setObjectName("comboBox_Select_Data")
        self.verticalLayout.addWidget(self.comboBox_Select_Data)
        self.label_Info = QtWidgets.QLabel(parent=Dialog_Get_Dummies)
        self.label_Info.setText("")
        self.label_Info.setObjectName("label_Info")
        self.verticalLayout.addWidget(self.label_Info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Apply = QtWidgets.QPushButton(parent=Dialog_Get_Dummies)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.horizontalLayout.addWidget(self.pushButton_Apply)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Dialog_Get_Dummies)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_Get_Dummies)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Get_Dummies)

    def retranslateUi(self, Dialog_Get_Dummies):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Get_Dummies.setWindowTitle(_translate("Dialog_Get_Dummies", "Rozdziel dane"))
        self.comboBox_Select_Data.setPlaceholderText(
            _translate("Dialog_Get_Dummies", "Wybierz kolumnę do rozdzielenia danych..."))
        self.pushButton_Apply.setText(_translate("Dialog_Get_Dummies", "Zastosuj"))
        self.pushButton_Cancel.setText(_translate("Dialog_Get_Dummies", "Anuluj"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog_Get_Dummies = QtWidgets.QDialog()
    ui = Ui_Dialog_Get_Dummies()
    ui.setupUi(Dialog_Get_Dummies)
    Dialog_Get_Dummies.show()
    sys.exit(app.exec())
