# Form implementation generated from reading ui file '.\change-headers.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_change_headers(object):
    def setupUi(self, Dialog_change_headers):
        Dialog_change_headers.setObjectName("Dialog_change_headers")
        Dialog_change_headers.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog_change_headers.resize(475, 205)
        Dialog_change_headers.setMinimumSize(QtCore.QSize(475, 205))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_change_headers)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_headers_list = QtWidgets.QComboBox(parent=Dialog_change_headers)
        self.comboBox_headers_list.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_headers_list.setObjectName("comboBox_headers_list")
        self.verticalLayout.addWidget(self.comboBox_headers_list)
        spacerItem = QtWidgets.QSpacerItem(5, 25, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_new_header_name = QtWidgets.QLineEdit(parent=Dialog_change_headers)
        self.lineEdit_new_header_name.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_new_header_name.setObjectName("lineEdit_new_header_name")
        self.verticalLayout.addWidget(self.lineEdit_new_header_name)
        self.label_info_text = QtWidgets.QLabel(parent=Dialog_change_headers)
        self.label_info_text.setMinimumSize(QtCore.QSize(0, 25))
        self.label_info_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_text.setObjectName("label_info_text")
        self.verticalLayout.addWidget(self.label_info_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Apply = QtWidgets.QPushButton(parent=Dialog_change_headers)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.horizontalLayout.addWidget(self.pushButton_Apply)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Dialog_change_headers)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_change_headers)
        self.pushButton_Cancel.clicked.connect(Dialog_change_headers.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_change_headers)

    def retranslateUi(self, Dialog_change_headers):
        _translate = QtCore.QCoreApplication.translate
        Dialog_change_headers.setWindowTitle(_translate("Dialog_change_headers", "Zmień nagłówki"))
        self.comboBox_headers_list.setPlaceholderText(_translate("Dialog_change_headers", "Wybierz nagłówek do zmiany nazwy..."))
        self.lineEdit_new_header_name.setPlaceholderText(_translate("Dialog_change_headers", "Wpisz nową nazwę nagłówka..."))
        self.label_info_text.setText(_translate("Dialog_change_headers", "Wybierz nagłówek kolumny do zmiany nazwy i podaj nową nazwę"))
        self.pushButton_Apply.setText(_translate("Dialog_change_headers", "Zastosuj"))
        self.pushButton_Cancel.setText(_translate("Dialog_change_headers", "Anuluj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_change_headers = QtWidgets.QDialog()
    ui = Ui_Dialog_change_headers()
    ui.setupUi(Dialog_change_headers)
    Dialog_change_headers.show()
    sys.exit(app.exec())
