# Form implementation generated from reading ui file '.\replace.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Replace(object):
    def setupUi(self, Dialog_Replace):
        Dialog_Replace.setObjectName("Dialog_Replace")
        Dialog_Replace.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog_Replace.resize(400, 340)
        Dialog_Replace.setMinimumSize(QtCore.QSize(400, 340))
        Dialog_Replace.setMaximumSize(QtCore.QSize(400, 340))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../images/app-icon/dex-icon-512x512.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        Dialog_Replace.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog_Replace)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_Replace)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_Column_List_Select = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_Column_List_Select.setObjectName("comboBox_Column_List_Select")
        self.verticalLayout.addWidget(self.comboBox_Column_List_Select)
        self.checkBox_Replace_All = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_Replace_All.setObjectName("checkBox_Replace_All")
        self.verticalLayout.addWidget(self.checkBox_Replace_All)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_Replace)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_Value_To_Replace = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_Value_To_Replace.setObjectName("lineEdit_Value_To_Replace")
        self.verticalLayout_2.addWidget(self.lineEdit_Value_To_Replace)
        self.checkBox_Value_Nan = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox_Value_Nan.setObjectName("checkBox_Value_Nan")
        self.verticalLayout_2.addWidget(self.checkBox_Value_Nan)
        self.checkBox_Value_Null = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.checkBox_Value_Null.setObjectName("checkBox_Value_Null")
        self.verticalLayout_2.addWidget(self.checkBox_Value_Null)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Dialog_Replace)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_New_Value = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_New_Value.setObjectName("lineEdit_New_Value")
        self.verticalLayout_3.addWidget(self.lineEdit_New_Value)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.label_Info = QtWidgets.QLabel(parent=Dialog_Replace)
        self.label_Info.setText("")
        self.label_Info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Info.setObjectName("label_Info")
        self.verticalLayout_4.addWidget(self.label_Info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Apply = QtWidgets.QPushButton(parent=Dialog_Replace)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.horizontalLayout.addWidget(self.pushButton_Apply)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Dialog_Replace)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_Replace)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Replace)

    def retranslateUi(self, Dialog_Replace):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Replace.setWindowTitle(_translate("Dialog_Replace", "Zamień"))
        self.groupBox.setTitle(_translate("Dialog_Replace", "1) Wybierz gdzie zamienić wartości: "))
        self.comboBox_Column_List_Select.setPlaceholderText(_translate("Dialog_Replace", "Wybierz kolumne..."))
        self.checkBox_Replace_All.setText(_translate("Dialog_Replace", "Zamień wartości w całym pliku"))
        self.groupBox_2.setTitle(_translate("Dialog_Replace", "2) Wybierz jakie wartości zamienić: "))
        self.checkBox_Value_Nan.setText(_translate("Dialog_Replace", "Wartości NaN"))
        self.checkBox_Value_Null.setText(_translate("Dialog_Replace", "Wartości puste"))
        self.groupBox_3.setTitle(_translate("Dialog_Replace", "3) Podaj na co zamienić wybrane wartości:"))
        self.pushButton_Apply.setText(_translate("Dialog_Replace", "Zastosuj"))
        self.pushButton_Cancel.setText(_translate("Dialog_Replace", "Anuluj"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog_Replace = QtWidgets.QDialog()
    ui = Ui_Dialog_Replace()
    ui.setupUi(Dialog_Replace)
    Dialog_Replace.show()
    sys.exit(app.exec())
