# Form implementation generated from reading ui file '.\rename-key-dataframe.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Rename_Key_Dataframe(object):
    def setupUi(self, Dialog_Rename_Key_Dataframe):
        Dialog_Rename_Key_Dataframe.setObjectName("Dialog_Rename_Key_Dataframe")
        Dialog_Rename_Key_Dataframe.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog_Rename_Key_Dataframe.resize(500, 200)
        Dialog_Rename_Key_Dataframe.setMinimumSize(QtCore.QSize(500, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_Rename_Key_Dataframe)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_Keys_List = QtWidgets.QComboBox(parent=Dialog_Rename_Key_Dataframe)
        self.comboBox_Keys_List.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_Keys_List.setObjectName("comboBox_Keys_List")
        self.verticalLayout.addWidget(self.comboBox_Keys_List)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_New_Key_Name = QtWidgets.QLineEdit(parent=Dialog_Rename_Key_Dataframe)
        self.lineEdit_New_Key_Name.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_New_Key_Name.setObjectName("lineEdit_New_Key_Name")
        self.verticalLayout.addWidget(self.lineEdit_New_Key_Name)
        self.label_info_text = QtWidgets.QLabel(parent=Dialog_Rename_Key_Dataframe)
        self.label_info_text.setMinimumSize(QtCore.QSize(0, 25))
        self.label_info_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_text.setObjectName("label_info_text")
        self.verticalLayout.addWidget(self.label_info_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Apply = QtWidgets.QPushButton(parent=Dialog_Rename_Key_Dataframe)
        self.pushButton_Apply.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.horizontalLayout.addWidget(self.pushButton_Apply)
        self.pushButton_Cancel = QtWidgets.QPushButton(parent=Dialog_Rename_Key_Dataframe)
        self.pushButton_Cancel.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout.addWidget(self.pushButton_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog_Rename_Key_Dataframe)
        self.pushButton_Cancel.clicked.connect(Dialog_Rename_Key_Dataframe.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Rename_Key_Dataframe)

    def retranslateUi(self, Dialog_Rename_Key_Dataframe):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Rename_Key_Dataframe.setWindowTitle(_translate("Dialog_Rename_Key_Dataframe", "Zmień nazwę zbioru danych"))
        self.comboBox_Keys_List.setPlaceholderText(_translate("Dialog_Rename_Key_Dataframe", "Wybierz zbiór do zmiany nazwy..."))
        self.lineEdit_New_Key_Name.setPlaceholderText(_translate("Dialog_Rename_Key_Dataframe", "Wpisz nową nazwę zbioru danych..."))
        self.label_info_text.setText(_translate("Dialog_Rename_Key_Dataframe", "Wybierz zbiór danych do zmiany nazwy i podaj nową nazwę zbioru"))
        self.pushButton_Apply.setText(_translate("Dialog_Rename_Key_Dataframe", "Zastosuj"))
        self.pushButton_Cancel.setText(_translate("Dialog_Rename_Key_Dataframe", "Anuluj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Rename_Key_Dataframe = QtWidgets.QDialog()
    ui = Ui_Dialog_Rename_Key_Dataframe()
    ui.setupUi(Dialog_Rename_Key_Dataframe)
    Dialog_Rename_Key_Dataframe.show()
    sys.exit(app.exec())
