# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/app-icon/dex-icon-512x512.png"), QtGui.QIcon.Mode.Normal,
                       QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add_file = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_add_file.setMinimumSize(QtCore.QSize(0, 150))
        self.button_add_file.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_add_file.setFont(font)
        self.button_add_file.setMouseTracking(True)
        self.button_add_file.setStyleSheet("QToolButton {\n"
                                           "        background-color: rgb(225,225,225);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(173,173,173);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 10%;\n"
                                           "          margin-bottom: 10%;\n"
                                           "          margin-right: 10%;\n"
                                           "          margin-left: 10%;\n"
                                           "}\n"
                                           " \n"
                                           "QToolButton:hover {\n"
                                           "        background-color: rgb(229,241,251);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(0,84,153);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 10%;\n"
                                           "          margin-bottom: 10%;\n"
                                           "          margin-right: 10%;\n"
                                           "          margin-left: 10%;\n"
                                           "    }\n"
                                           "\n"
                                           "QToolButton:pressed {\n"
                                           "        background-color: rgb(204,228,247);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(0,84,153);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 1%;\n"
                                           "          margin-bottom: 1%;\n"
                                           "          margin-right: 1%;\n"
                                           "          margin-left: 1%;\n"
                                           "    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/main-window/mw-add-file.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_add_file.setIcon(icon1)
        self.button_add_file.setIconSize(QtCore.QSize(70, 70))
        self.button_add_file.setCheckable(False)
        self.button_add_file.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_add_file.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_add_file.setObjectName("button_add_file")
        self.horizontalLayout.addWidget(self.button_add_file)
        self.button_modify_data = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_modify_data.setMinimumSize(QtCore.QSize(200, 150))
        self.button_modify_data.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_modify_data.setFont(font)
        self.button_modify_data.setStyleSheet("QToolButton {\n"
                                              "        background-color: rgb(225,225,225);\n"
                                              "        color: black;\n"
                                              "        padding: 50%;\n"
                                              "        border: 1px solid rgb(173,173,173);\n"
                                              "        border-radius: 25%;\n"
                                              "          margin-top: 10%;\n"
                                              "          margin-bottom: 10%;\n"
                                              "          margin-right: 10%;\n"
                                              "          margin-left: 10%;\n"
                                              "}\n"
                                              " \n"
                                              "QToolButton:hover {\n"
                                              "        background-color: rgb(229,241,251);\n"
                                              "        color: black;\n"
                                              "        padding: 50%;\n"
                                              "        border: 1px solid rgb(0,84,153);\n"
                                              "        border-radius: 25%;\n"
                                              "          margin-top: 10%;\n"
                                              "          margin-bottom: 10%;\n"
                                              "          margin-right: 10%;\n"
                                              "          margin-left: 10%;\n"
                                              "    }\n"
                                              "\n"
                                              "QToolButton:pressed {\n"
                                              "        background-color: rgb(204,228,247);\n"
                                              "        color: black;\n"
                                              "        padding: 50%;\n"
                                              "        border: 1px solid rgb(0,84,153);\n"
                                              "        border-radius: 25%;\n"
                                              "          margin-top: 1%;\n"
                                              "          margin-bottom: 1%;\n"
                                              "          margin-right: 1%;\n"
                                              "          margin-left: 1%;\n"
                                              "    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/main-window/mw-modify-data.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_modify_data.setIcon(icon2)
        self.button_modify_data.setIconSize(QtCore.QSize(70, 70))
        self.button_modify_data.setCheckable(False)
        self.button_modify_data.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_modify_data.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_modify_data.setObjectName("button_modify_data")
        self.horizontalLayout.addWidget(self.button_modify_data)
        self.button_analysis_data = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_analysis_data.setMinimumSize(QtCore.QSize(200, 150))
        self.button_analysis_data.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_analysis_data.setFont(font)
        self.button_analysis_data.setStyleSheet("QToolButton {\n"
                                                "        background-color: rgb(225,225,225);\n"
                                                "        color: black;\n"
                                                "        padding: 50%;\n"
                                                "        border: 1px solid rgb(173,173,173);\n"
                                                "        border-radius: 25%;\n"
                                                "          margin-top: 10%;\n"
                                                "          margin-bottom: 10%;\n"
                                                "          margin-right: 10%;\n"
                                                "          margin-left: 10%;\n"
                                                "}\n"
                                                " \n"
                                                "QToolButton:hover {\n"
                                                "        background-color: rgb(229,241,251);\n"
                                                "        color: black;\n"
                                                "        padding: 50%;\n"
                                                "        border: 1px solid rgb(0,84,153);\n"
                                                "        border-radius: 25%;\n"
                                                "          margin-top: 10%;\n"
                                                "          margin-bottom: 10%;\n"
                                                "          margin-right: 10%;\n"
                                                "          margin-left: 10%;\n"
                                                "    }\n"
                                                "\n"
                                                "QToolButton:pressed {\n"
                                                "        background-color: rgb(204,228,247);\n"
                                                "        color: black;\n"
                                                "        padding: 50%;\n"
                                                "        border: 1px solid rgb(0,84,153);\n"
                                                "        border-radius: 25%;\n"
                                                "          margin-top: 1%;\n"
                                                "          margin-bottom: 1%;\n"
                                                "          margin-right: 1%;\n"
                                                "          margin-left: 1%;\n"
                                                "    }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/main-window/mw-data-analysis.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_analysis_data.setIcon(icon3)
        self.button_analysis_data.setIconSize(QtCore.QSize(70, 70))
        self.button_analysis_data.setCheckable(False)
        self.button_analysis_data.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_analysis_data.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_analysis_data.setObjectName("button_analysis_data")
        self.horizontalLayout.addWidget(self.button_analysis_data)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_settings = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_settings.setMinimumSize(QtCore.QSize(200, 150))
        self.button_settings.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_settings.setFont(font)
        self.button_settings.setStyleSheet("QToolButton {\n"
                                           "        background-color: rgb(225,225,225);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(173,173,173);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 10%;\n"
                                           "          margin-bottom: 10%;\n"
                                           "          margin-right: 10%;\n"
                                           "          margin-left: 10%;\n"
                                           "}\n"
                                           " \n"
                                           "QToolButton:hover {\n"
                                           "        background-color: rgb(229,241,251);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(0,84,153);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 10%;\n"
                                           "          margin-bottom: 10%;\n"
                                           "          margin-right: 10%;\n"
                                           "          margin-left: 10%;\n"
                                           "    }\n"
                                           "\n"
                                           "QToolButton:pressed {\n"
                                           "        background-color: rgb(204,228,247);\n"
                                           "        color: black;\n"
                                           "        padding: 50%;\n"
                                           "        border: 1px solid rgb(0,84,153);\n"
                                           "        border-radius: 25%;\n"
                                           "          margin-top: 1%;\n"
                                           "          margin-bottom: 1%;\n"
                                           "          margin-right: 1%;\n"
                                           "          margin-left: 1%;\n"
                                           "    }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/main-window/mw-settings.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_settings.setIcon(icon4)
        self.button_settings.setIconSize(QtCore.QSize(70, 70))
        self.button_settings.setCheckable(False)
        self.button_settings.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_settings.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_settings.setObjectName("button_settings")
        self.horizontalLayout_2.addWidget(self.button_settings)
        self.button_help = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_help.setMinimumSize(QtCore.QSize(200, 150))
        self.button_help.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_help.setFont(font)
        self.button_help.setStyleSheet("QToolButton {\n"
                                       "        background-color: rgb(225,225,225);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(173,173,173);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 10%;\n"
                                       "          margin-bottom: 10%;\n"
                                       "          margin-right: 10%;\n"
                                       "          margin-left: 10%;\n"
                                       "}\n"
                                       " \n"
                                       "QToolButton:hover {\n"
                                       "        background-color: rgb(229,241,251);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(0,84,153);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 10%;\n"
                                       "          margin-bottom: 10%;\n"
                                       "          margin-right: 10%;\n"
                                       "          margin-left: 10%;\n"
                                       "    }\n"
                                       "\n"
                                       "QToolButton:pressed {\n"
                                       "        background-color: rgb(204,228,247);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(0,84,153);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 1%;\n"
                                       "          margin-bottom: 1%;\n"
                                       "          margin-right: 1%;\n"
                                       "          margin-left: 1%;\n"
                                       "    }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/main-window/mw-help.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_help.setIcon(icon5)
        self.button_help.setIconSize(QtCore.QSize(70, 70))
        self.button_help.setCheckable(False)
        self.button_help.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_help.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_help.setObjectName("button_help")
        self.horizontalLayout_2.addWidget(self.button_help)
        self.button_exit = QtWidgets.QToolButton(parent=self.centralwidget)
        self.button_exit.setMinimumSize(QtCore.QSize(200, 150))
        self.button_exit.setMaximumSize(QtCore.QSize(3000, 1500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_exit.setFont(font)
        self.button_exit.setStyleSheet("QToolButton {\n"
                                       "        background-color: rgb(225,225,225);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(173,173,173);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 10%;\n"
                                       "          margin-bottom: 10%;\n"
                                       "          margin-right: 10%;\n"
                                       "          margin-left: 10%;\n"
                                       "}\n"
                                       " \n"
                                       "QToolButton:hover {\n"
                                       "        background-color: rgb(229,241,251);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(0,84,153);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 10%;\n"
                                       "          margin-bottom: 10%;\n"
                                       "          margin-right: 10%;\n"
                                       "          margin-left: 10%;\n"
                                       "    }\n"
                                       "\n"
                                       "QToolButton:pressed {\n"
                                       "        background-color: rgb(204,228,247);\n"
                                       "        color: black;\n"
                                       "        padding: 50%;\n"
                                       "        border: 1px solid rgb(0,84,153);\n"
                                       "        border-radius: 25%;\n"
                                       "          margin-top: 1%;\n"
                                       "          margin-bottom: 1%;\n"
                                       "          margin-right: 1%;\n"
                                       "          margin-left: 1%;\n"
                                       "    }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/main-window/mw-exit.svg"), QtGui.QIcon.Mode.Normal,
                        QtGui.QIcon.State.Off)
        self.button_exit.setIcon(icon6)
        self.button_exit.setIconSize(QtCore.QSize(70, 70))
        self.button_exit.setCheckable(False)
        self.button_exit.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.button_exit.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout_2.addWidget(self.button_exit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dex"))
        self.button_add_file.setText(_translate("MainWindow", "Dodaj\n"
                                                              "plik"))
        self.button_modify_data.setText(_translate("MainWindow", "Modyfikuj\n"
                                                                 "dane"))
        self.button_analysis_data.setText(_translate("MainWindow", "Analizuj\n"
                                                                   "dane"))
        self.button_settings.setText(_translate("MainWindow", "Ustawienia"))
        self.button_help.setText(_translate("MainWindow", "Pomoc"))
        self.button_exit.setText(_translate("MainWindow", "Wyjście"))
